server:
  port: 8080

logging:
  level:
    com.hohohehe.checktracker: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.orm.jdbc.bind: trace

spring:
  application:
    name: check-tracker
  datasource:
    url: jdbc:mysql://localhost:3300/checkTracker?serverTimezone=Asia/Seoul
    username: checkTracker
    password: checkTracker
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

jwt:
  issuer: temp                                     #추후 github secrets로 대체
  secret_key: temp-temp-temp-temp-temp-temp-temp   #추후 github secrets로 대체
  access_token_expiration: 900000                  # 15분
